# Generated by Django 5.2.12 on 2026-03-28 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('rarity', models.CharField(choices=[('common', '普通'), ('rare', '稀有'), ('epic', '史詩'), ('legendary', '傳說')], max_length=10)),
                ('emoji', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'cat_species',
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GachaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('cat_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha.catspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gacha_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gacha_history',
                'ordering': ['-pulled_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_level', models.IntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('cat_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha.catspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cats',
                'unique_together': {('user', 'cat_species')},
            },
        ),
    ]
