# Generated by Django 5.2.12 on 2026-03-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catspecies',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
